name = "code-mon-space"
main = "worker.js" # or src/index.js
compatibility_date = "2025-12-28"
[[kv_namespaces]]
binding = "APP"
id = "16cae66906a24d1f8862fad185187cd9"
[[kv_namespaces]]
binding = "Pass"
id = "144779e18a7e4a7c898f55f679ee825d"
[[kv_namespaces]]
binding = "FILES"
id = "c70879b43b304bef9c0344fed6975247"
