name = "code-mon-space"
main = "worker.js"
compatibility_date = "2025-12-28"

workers_dev = true

routes = [
  { pattern = "*.code-mon-space.shop/*", zone_name = "code-mon-space.shop" }
]
[[kv_namespaces]]
binding = "APP"
id = "16cae66906a24d1f8862fad185187cd9"
[[kv_namespaces]]
binding = "Pass"
id = "144779e18a7e4a7c898f55f679ee825d"
[[kv_namespaces]]
binding = "FILES"
id = "c70879b43b304bef9c0344fed6975247"
[[kv_namespaces]]
binding = "STORAGE"
id = "5163935978d34b47ac564672381a718d"
